### ISSUE TITLE
Cannot find models/densepose/args_dict.pt

### ISSUE THREAD

**Issue by cgusti** [MartinPernus/FICE#1]
Hi Martin! 

Hope you are having a great day. Me and my partner want to clone your github to study FICE further for our masters capstone project. We followed all installation instructions in your readme, but we came across a `FileNotFoundError: [Errno 2] No such file or directory: '/content/FICE-Implementation/models/densepose/args_dict.pt'` when running 

`!python main.py --input_dir imgs/input --description "long sleeve silk crepe de chine shirt featuring graphic pattern printed in tones of blue"`

Here is the full error log: 
`Importing StyleGAN modules
StyleGAN modules imported
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    trainer = Trainer(opt)

  File "/content/FICE-Implementation/trainer.py", line 79, in __init__
    self.model = Model(clip_model=opt.clip_model).eval().requires_grad_(False)

  File "/content/FICE-Implementation/trainer.py", line 53, in __init__
    self.densenet = DenseNet()

  File "/content/FICE-Implementation/models/densepose/model.py", line 34, in __init__
    args = torch.load(os.path.join(thisdir, 'args_dict.pt'))

  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:

  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)

  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))

FileNotFoundError: [Errno 2] No such file or directory: '/content/FICE-Implementation/models/densepose/args_dict.pt'`

We looked through your github repository and could not find "models/densepose/args_dict.pt" file. Do you have any insight on where we can find this file and what it might contain?

**Comment by giuseppecartella** [comment]
Hi @cgusti, how did you load .cpp and .cu files? In debugging using torch.utils.cpp_extensions.load() function the program stops. 
Did you encounter the same problem?
Thank you

**Comment by MartinPernus** [comment]
Hi,

Sorry for the late reply, I am currently vacationing. Try this link to
download the file:
https://www.dropbox.com/s/p31n7jc2w20cpkv/args_dict.pt?dl=0

I will fix this properly once I get back home in a week or so.

**Comment by MartinPernus** [comment]
This file is now by default in the repository.
