### ISSUE TITLE
Is function "process_gen" and "process" used in trainer.py?

### ISSUE THREAD

**Issue by zsMoonshine** [MartinPernus/FICE#3]
![image](https://user-images.githubusercontent.com/58875066/217751684-0418653b-03a0-4e45-9270-485a7b2e509c.png)

And could you please give me some hints or examples on how to train the model? By reading class "Trainer" I see the structure of method mentioned in FICE paper, but I still don't know how to get the train start.

I'm a student who is new to deeplearning and very interested in your research, please help me if it's convenient.

**Comment by MartinPernus** [comment]
Hi.

This repository only provides trained models for inference purposes.

Would you like to train the models from scratch?

**Comment by zsMoonshine** [comment]
Thanks for your so rapid reply. Yes, I'd like to train the model from scratch using some other datasets. It'll be quite helpful if you could provide me some training codes.

**Comment by MartinPernus** [comment]
I see. This seems to be a popular request. I will make sure to provide the training code in the near future.

**Comment by zsMoonshine** [comment]
Thank you very much. I'm looking forward to that. Thanks for your hard work and enthusiasm.

**Comment by zsMoonshine** [comment]
And may you please send some training codes(Unorganized ones is okay) to my educational email(******@****.****.***.**)? This will also help a lot.

**Comment by MartinPernus** [comment]
Done.

**Comment by zsMoonshine** [comment]
Thanks for your reply and share. And I need to spend some time reading them. 
I think I will ask questions via email after that. Thanks for your patience and ethusiasm.

**Comment by leto-hub** [comment]
Sorry to bothering, I am a student who is working on Multimodal domain. I greatly admire your creative work in the field of image editing and want to train this model from scratch. Cound you please send the training codes to my email(nmx@tju.edu.cn) if it doesn't bother you?

**Comment by MartinPernus** [comment]
Commit 7354216 adds additional instructions about training from scratch!

**Comment by zsMoonshine** [comment]
Thanks a lot👍
