### ISSUE TITLE
About StyleCLIP's global direction StyleCLIP Implementation in paper 

### ISSUE THREAD

**Issue by zsMoonshine** [MartinPernus/FICE#5]
Hi, Martin. With your help I have successfully trained FICE's models from scratch. And I noticed that in the [FICE paper](http://arxiv.org/abs/2301.02110), a global direction has been used on several GAN inversion encoders(pSp, E4e, ReStyle, HyperStyle).

I've tried global direction using code provided by [styleclip's global_pytorch](https://github.com/orpatashnik/StyleCLIP/tree/main/global_directions). And I noticed that they use e4e.
But an error happened, which indicates that the keys in weight dict are not right. 

I guess that it's because the stylegan2 checkpoint is based on stylegan2-ada and the e4e in FICE is trained on stylegan2-ada too. 
I knew that this is slight modification in e4e's psp.py, but I don't know if it's related to the error, or it's just for the reason of the diffrence between stylegan2-ada and stylegan2.
![image](https://user-images.githubusercontent.com/58875066/228548373-687650ef-ecb1-44d7-b529-fe6e6252db09.png)

![image](https://user-images.githubusercontent.com/58875066/228546879-0520e8e6-b8e2-408b-98f4-7207de124e30.png)

So how did you implement the global direction? To train a new model using the official stylegan2 or do something to change weight dict? Looking forward to your reply. Thanks a lot.

**Comment by MartinPernus** [comment]
Hi!

You are correct, StyleCLIP is implemented from scratch. The already existing baseline would not work on fashion data since it is trained on another dataset.

Since I don't think this is a popular request I was not intending to note the StyleCLIP-related instructions in README. I would instead suggest to email me and I will send instructions associated with its implementation.

Best,
Martin

**Comment by qu-bit1** [comment]
@zsMoonshine I am facing some problems in training FICE from scratch, can you share the code you used for training. I am pretty new and am unable to analyse this whole codebase

**Comment by zsMoonshine** [comment]
> @zsMoonshine I am facing some problems in training FICE from scratch, can you share the code you used for training. I am pretty new and am unable to analyse this whole codebase

Your email address please. And you can get help to train the model from scratch refering to this Commit[https://github.com/MartinPernus/FICE/commit/7354216f462edc71854bfdfe4fa617bf5531b10f adds additional instructions about training from scratch!]

**Comment by qu-bit1** [comment]
@zsMoonshine arorasagar912@gmail.com , thanks I'll refer to the commit too
