### ISSUE TITLE
Can I get VITON dataset?

### ISSUE THREAD

**Issue by seunghee-han** [MartinPernus/FICE#6]
Hello,  have read your paper, and I think your paper is very good.
so I've implemented the code, and I want to even train the model myself.
But to do that, I need the VITON dataset, but I can't find.

![스크린샷 2023-04-30 20-07-14](https://user-images.githubusercontent.com/54052702/235349702-ed6a865c-4b02-472e-9556-61208d5cc4f6.png)

Can i get 'viton.pkl' ?

Thank You.

**Comment by MartinPernus** [comment]
Kaggle link is available [here](https://www.kaggle.com/datasets/rkuo2000/viton-dataset).
